Update base image to CentOS Stream 8 (NO_JIRA)
ccdc-opensource/packer-ccdc-basebox-centos-8 pull request #1
Opened 2022-03-01 21:00 UTC by florianpiesche

2022-03-02 08:20 UTC, emyers-ccdc approved these changes

2022-03-02 08:55 UTC, rockdreamer requested changes

2022-03-02 08:55 UTC, rockdreamer commented on centos-8-x86_64.json
> +    "iso_name": "CentOS-Stream-8-x86_64-latest-dvd1.iso",
This looks like something that changes constantly. Is there no timestamped version?

2022-03-03 11:20 UTC, florianpiesche commented on centos-8-x86_64.json
> +    "iso_name": "CentOS-Stream-8-x86_64-latest-dvd1.iso",
Good point! Sorted.

2022-04-27 14:41 UTC, merged